Different code coverage report generator

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,13 +36,15 @@ jobs:
         run: dotnet build --configuration Release
 
       - name: Run unit tests
-        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage
+        run: |
+          dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage
+          Move-Item coverage/*/coverage.cobertura.xml coverage/
 
       - name: Upload unit test coverage
         uses: actions/upload-artifact@v4
         with:
           name: coverage
-          path: coverage/**/coverage.cobertura.xml
+          path: coverage/coverage.cobertura.xml
           if-no-files-found: error
 
       - name: Prepare installer
@@ -71,22 +73,21 @@ jobs:
           name: coverage
           path: coverage
 
-      - name: Code Coverage Report
-        uses: irongut/CodeCoverageSummary@v1.3.0
+      - name: Generate Coverage Report
+        uses: clearlyip/code-coverage-report-action@v4
+        id: code_coverage_report_action
+        if: ${{ github.actor != 'dependabot[bot]'}}
         with:
-          filename: coverage/**/coverage.cobertura.xml
+          filename: coverage/coverage.cobertura.xml
           badge: true
-          # TODO fail_below_min: true
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: true
-          indicators: true
-          output: both
-          thresholds: '60 80'
+          # TODO overall_coverage_fail_threshold: 70
+          # TODO file_coverage_error_min: 80
+          # TODO file_coverage_warning_max: 90
+          # TODO fail_on_negative_difference: true
 
-      - name: Add Coverage PR Comment
+      - name: Add Coverage Comment to PR
         uses: marocchino/sticky-pull-request-comment@v2
-        if: github.event_name == 'pull_request'
+        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
         with:
           recreate: true
           path: code-coverage-results.md
